version: "3.7"

services:
  etlxci:
    container_name: etlxci
    image: kedikx/etlxci:latest
    build:
      context: ./ci
    init: True
    command: tail -f /dev/null
    volumes:
      - ..:/etlxci

  mysql:
    container_name: mysql
    image: mysql:5.7.12
    network_mode: "service:etlxci"
    environment:
      - MYSQL_ROOT_PASSWORD=test
    healthcheck:
      test: mysql -ptest -e "show databases"
