# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: etlx-build

on:
  push:
    branches: [ develop, feature/dbi ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6']

    services:
      mysql:
        image: mysql
        ports:
          - 3306
        env:
          MYSQL_USER: etlx_user
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: etlx_test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=5s --health-retries=5

      postgres:
        image: postgres
        ports:
          - 5432
        env:
          POSTGRES_USER: etlx_user
          POSTGRES_PASSWORD: test
          POSTGRES_DB: etlx_test
        options: --health-cmd="pg_isready" --health-interval=5s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 coverage
        python ./setup.py -q requirements --all > requirements.txt
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run setup.py
      run: |
        python ./setup.py --version
    - name: Run tests
      env:
        ETLX_TEST_MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        ETLX_TEST_POSGRES_PORT: ${{ job.services.postgres.ports[5432] }}
      run: |
        coverage run -m unittest discover -t . -s ./etlx_tests
    - name: Upload codecov report
      uses: codecov/codecov-action@v1
      